#!/bin/sh
gsettings set org.gnome.Vino prompt-enabled false
gsettings set org.gnome.Vino authentication-methods [\'vnc\']
gsettings set org.gnome.Vino vnc-password 'YWlsMjAyMA=='
/usr/lib/vino/./vino-server
